import { resolveGrammar, SUPPORTED_GRAMMARS } from '../../../webview/highlighting/languageRegistry';

describe('highlighting language registry', () => {
  it.each([
    ['TS', 'typescript'],
    ['js', 'javascript'],
    ['tsx', 'typescript'],
    ['JSONC', 'json'],
    ['html', 'xml'],
    ['svg', 'xml'],
    ['yml', 'yaml'],
    ['console', 'shell'],
    ['c++', 'cpp'],
    ['c#', 'csharp'],
    ['pycon', 'python-repl'],
    ['toml', 'ini'],
  ])('resolves %s to %s', (authored, expected) => {
    expect(resolveGrammar(authored)).toBe(expected);
  });
  it.each([
    '',
    'text',
    'txt',
    'plaintext',
    'none',
    'nohighlight',
    'unknown',
    'ts title="x"',
    '__proto__',
    'constructor',
  ])('does not guess %s', authored => {
    expect(resolveGrammar(authored)).toBeNull();
  });
  it('preserves all currently effective non-plain canonical grammar families', () => {
    expect(SUPPORTED_GRAMMARS).toHaveLength(36);
    expect(SUPPORTED_GRAMMARS).toEqual(
      expect.arrayContaining(['arduino', 'php-template', 'yaml', 'python-repl', 'graphql', 'wasm'])
    );
  });
});

// Alias inventory captured from the unmodified 1b8244b runtime before migration.
const previousAliases = {
  arduino: 'arduino',
  ino: 'arduino',
  bash: 'bash',
  sh: 'bash',
  zsh: 'bash',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  'c++': 'cpp',
  'h++': 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  hxx: 'cpp',
  cxx: 'cpp',
  csharp: 'csharp',
  cs: 'csharp',
  'c#': 'csharp',
  css: 'css',
  diff: 'diff',
  patch: 'diff',
  go: 'go',
  golang: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  ini: 'ini',
  toml: 'ini',
  java: 'java',
  jsp: 'java',
  javascript: 'javascript',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  kotlin: 'kotlin',
  kt: 'kotlin',
  kts: 'kotlin',
  less: 'less',
  lua: 'lua',
  makefile: 'makefile',
  mk: 'makefile',
  mak: 'makefile',
  make: 'makefile',
  markdown: 'markdown',
  md: 'markdown',
  mkdown: 'markdown',
  mkd: 'markdown',
  objectivec: 'objectivec',
  mm: 'objectivec',
  objc: 'objectivec',
  'obj-c': 'objectivec',
  'obj-c++': 'objectivec',
  'objective-c++': 'objectivec',
  perl: 'perl',
  pl: 'perl',
  pm: 'perl',
  php: 'php',
  'php-template': 'php-template',
  plaintext: 'plaintext',
  text: 'plaintext',
  txt: 'plaintext',
  python: 'python',
  py: 'python',
  gyp: 'python',
  ipython: 'python',
  'python-repl': 'python-repl',
  pycon: 'python-repl',
  r: 'r',
  ruby: 'ruby',
  rb: 'ruby',
  gemspec: 'ruby',
  podspec: 'ruby',
  thor: 'ruby',
  irb: 'ruby',
  rust: 'rust',
  rs: 'rust',
  scss: 'scss',
  shell: 'shell',
  console: 'shell',
  shellsession: 'shell',
  sql: 'sql',
  swift: 'swift',
  typescript: 'typescript',
  ts: 'typescript',
  tsx: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  vbnet: 'vbnet',
  vb: 'vbnet',
  wasm: 'wasm',
  xml: 'xml',
  html: 'xml',
  xhtml: 'xml',
  rss: 'xml',
  atom: 'xml',
  xjb: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  plist: 'xml',
  wsf: 'xml',
  svg: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
};

it.each(Object.entries(previousAliases))('preserves original alias %s', (alias, grammar) => {
  expect(resolveGrammar(alias)).toBe(grammar === 'plaintext' ? null : grammar);
});
