/**
 * Copyright (c) 2025-2026 Concret.io
 * Licensed under the MIT License. See LICENSE in the project root.
 * Lightweight snapshot of Lowlight 2.9 common grammars plus the editor's existing
 * highlight.js 11.12 overrides. No grammar code belongs on the typing thread.
 */

const GRAMMAR_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  arduino: 'arduino',
  ino: 'arduino',
  bash: 'bash',
  sh: 'bash',
  zsh: 'bash',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  'c++': 'cpp',
  'h++': 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  hxx: 'cpp',
  cxx: 'cpp',
  csharp: 'csharp',
  cs: 'csharp',
  'c#': 'csharp',
  css: 'css',
  diff: 'diff',
  patch: 'diff',
  go: 'go',
  golang: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  ini: 'ini',
  toml: 'ini',
  java: 'java',
  jsp: 'java',
  javascript: 'javascript',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  kotlin: 'kotlin',
  kt: 'kotlin',
  kts: 'kotlin',
  less: 'less',
  lua: 'lua',
  makefile: 'makefile',
  mk: 'makefile',
  mak: 'makefile',
  make: 'makefile',
  markdown: 'markdown',
  md: 'markdown',
  mkdown: 'markdown',
  mkd: 'markdown',
  objectivec: 'objectivec',
  mm: 'objectivec',
  objc: 'objectivec',
  'obj-c': 'objectivec',
  'obj-c++': 'objectivec',
  'objective-c++': 'objectivec',
  perl: 'perl',
  pl: 'perl',
  pm: 'perl',
  php: 'php',
  'php-template': 'php-template',
  python: 'python',
  py: 'python',
  gyp: 'python',
  ipython: 'python',
  'python-repl': 'python-repl',
  pycon: 'python-repl',
  r: 'r',
  ruby: 'ruby',
  rb: 'ruby',
  gemspec: 'ruby',
  podspec: 'ruby',
  thor: 'ruby',
  irb: 'ruby',
  rust: 'rust',
  rs: 'rust',
  scss: 'scss',
  shell: 'shell',
  console: 'shell',
  shellsession: 'shell',
  sql: 'sql',
  swift: 'swift',
  typescript: 'typescript',
  ts: 'typescript',
  tsx: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  vbnet: 'vbnet',
  vb: 'vbnet',
  wasm: 'wasm',
  xml: 'xml',
  html: 'xml',
  xhtml: 'xml',
  rss: 'xml',
  atom: 'xml',
  xjb: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  plist: 'xml',
  wsf: 'xml',
  svg: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
});
export const SUPPORTED_GRAMMARS: readonly string[] = Object.freeze(
  Array.from(new Set(Object.values(GRAMMAR_ALIASES)))
);

/** Resolve a fence's first authored token without guessing or changing its source. */
export function resolveGrammar(authoredFirstToken: string): string | null {
  const normalized = authoredFirstToken.trim().toLowerCase();
  return Object.prototype.hasOwnProperty.call(GRAMMAR_ALIASES, normalized)
    ? GRAMMAR_ALIASES[normalized]
    : null;
}
